### ISSUE TITLE
Passing a URL with brackets to curl

### ISSUE THREAD

**Issue by sjuniorti** [ugobriasco/gastronomycon-server#24]
your CURL example isn't working, reference: https://stackoverflow.com/questions/8333920/passing-a-url-with-brackets-to-curl

😄

**Comment by ugobriasco** [comment]
Fixed, see:
https://gastronomycon.matchyourtie.com/
https://github.com/ugobriasco/gastronomycon-server/wiki/Gastronomycon-API-v1.0-reference
